language: objective-c
osx_image: xcode10.1

podfile: Example/Podfile

before_install:
  - echo $(which wstest)
  - gem install cocoapods -v '1.2.1'
  - pod --version

env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=12.0,name=iPhone X"    POD_LINT="YES"
    - DESTINATION="platform=iOS Simulator,OS=11.0.1,name=iPhone 8"  POD_LINT="NO"
    - DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7"    POD_LINT="NO"
    - DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"     POD_LINT="NO"
    - DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 4S"    POD_LINT="NO"

script:
  - xcodebuild -workspace Example/NSStringMask.xcworkspace -scheme NSStringMask-Example -destination "$DESTINATION" build
  - xcodebuild -workspace Example/NSStringMask.xcworkspace -scheme NSStringMask-Example -destination "$DESTINATION" test

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
    pod lib lint --verbose --allow-warnings;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'NSStringMask'
